AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Application Template: Crea la inftaestructura basica. El bucket , la VPC la taba DB y...

##################3
##Metadata
##################3

Metadata:
  Licensce: Apache-2.0

######################
# Parameters section
######################

Parameters:
# Table:
  HashKeyElementName:
    Type: String  
    AllowedPattern: '[a-zA-z0-9]*'
    MinLength: "1"
    MaxLength: "2048"
    ConstraintDescription: must contain only alphanumeric characters

  HashKeyElementType:
    Description: HashType Primarykey Type
    Type: String
    Default: S
    AllowedValues: '[S|N]' # AllowedPattern
    MinLength: "1"
    MaxLength: "1"
    ConstraintDescription: must be either S or Name

  ReadCapacityUnits:
    Description: Provisioned read throughput
    Type: Number
    Default: "5"
    MinValue: "5"
    MaxValue: "10000"
    ConstraintDescription: must be between 5 and 10000

  WriteCapacityUnits:
    Description: Provisioned write throughput
    Type: Number
    Default: "10"
    MinValue: "5"
    MaxValue: "10000"
    ConstraintDescription: must be between 5 and 10000



######################
# Resources section
######################


Resources:
  ################
  #DynamoDBTTABLE
  ##############3
  myDynamoDBTable:

    Type: AWS::DynamoDB::Table
    Properties:

      AttributeDefinitions:
        - AttributeName: !Ref HashKeyElementName
          AttributeType: !Ref HashKeyElementType

      KeySchema:
        - AttributeName: !Ref HashKeyElementName
          KeyType: HASH

      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacityUnits
        WriteCapacityUnits: !Ref WriteCapacityUnits

      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
    
      TableName: Measures

  #########
  # Bucket
  ########
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: proy-marmenor-csv-raw

Outputs:
  TableName:
    Description: La Tabla Measures se ha creado correctamente
    Value: !Ref myDynamoDBTable
  BucketName:
    Description: El Bucket proy-marmenor-csv-raw de S3 ha sido creado correctamente
    Value: !Ref S3Bucket




