AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Application Template: Crea la infraestructura básica (DB, S3, VPC, SNS) e integra la función Lambda.

##################
## Metadata
##################

Metadata:
  License: Apache-2.0

######################
# Parameters section
######################

Parameters:

  ExistingRoleArn:
    Type: String
    Description: ARN del rol IAM de ejecución existente (LabRole).

    Default: arn:aws:iam::123456789012:role/LabRole
  
  # AMI
  AmazonLinuxAMIID:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2


######################
# Resources section
######################

Resources:
  ################
  # DynamoDB TABLE
  ################

  myDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: monthYear
          AttributeType: S 
      KeySchema:
        - AttributeName: monthYear
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 20 #!Ref ReadCapacityUnits
        WriteCapacityUnits: 20 
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TableName: Measures

  #########
  # Bucket
  #########
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "proy-marmenor-codebucket-${AWS::AccountId}"


  #####################
  #VPC 
  ####################
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: 192.168.0.0/16
      Tags:
        - Key: Name
          Value: proy-marmenor-vpc

  ## Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
    
  # NAT Gateway y Elastic IP
  NatGatewayEIP:
    Type: AWS::EC2::EIP
    DependsOn: VPCGatewayAttachment
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: proy-Nat-eip

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnet1
      Tags:
        - Key: Name
          Value: !Sub proy-nat-gateway

  ## Public Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: proy-Public-rt

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  
  PrivateRouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId: !Ref VPC
        Tags:
          - Key: Name
            Value: proy-Private-rt

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

  ## Public Subnet
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 192.168.0.0/24
      AvailabilityZone: !Select 
        - 0
        - !GetAZs
          Ref: AWS::Region
      Tags:
        - Key: Name
          Value: proy-PublicSubnet1

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  # segunda public subnet
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 192.168.3.0/24
      AvailabilityZone: !Select 
        - 1
        - !GetAZs
          Ref: AWS::Region
      Tags:
        - Key: Name
          Value: proy-PublicSubnet2

  PublicSubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable
  
  # privates subnets:
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 192.168.1.0/24
      AvailabilityZone: !Select 
        - 0
        - !GetAZs
          Ref: AWS::Region
      Tags:
        - Key: Name
          Value: proy-PrivateSubnet1
  
  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 192.168.2.0/24
      AvailabilityZone: !Select 
        - 1
        - !GetAZs
          Ref: AWS::Region
      Tags:
        - Key: Name
          Value: proy-PrivateSubnet2

  PrivateSubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable

  ## SecurityGroup
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Grupo de seguridad para el balanceador de carga
      GroupName: proy-alb-sg
      VpcId: !Ref VPC
      SecurityGroupIngress: # reglas de entrada
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: Allow HTTP 
      SecurityGroupEgress: #  trafico de salida
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
      Tags:
        - Key: Name
          Value: proy-alb-sg

  PrivateFlaskSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Grupo de seguridad para las instancias
      GroupName: proy-instances-sg
      VpcId: !Ref VPC
      SecurityGroupIngress: # reglas de entrada
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref ALBSecurityGroup
          Description: Trafico entre instancias y el balanceador
      SecurityGroupEgress: #  trafico de salida
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
      Tags:
        - Key: Name
          Value: proy-instances-sg

    # Grupo de seguridad temporal para la DockerInstance (SSH y testeo local)
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: proy-instanceSecurityGroup
      GroupDescription: Acceso SSH y testeo Flask
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
    

  ## Instances:
  DokerInstace:
    Type: AWS::EC2::Instance
    DependsOn: S3Bucket
    Properties:
      InstanceType: t3.micro
      ImageId: !Ref AmazonLinuxAMIID
      KeyName: proy-marmenor
      IamInstanceProfile: "LabInstanceProfile"
      NetworkInterfaces:
        - GroupSet:
            - !Ref InstanceSecurityGroup
          AssociatePublicIpAddress: true
          DeviceIndex: 0
          DeleteOnTermination: true
          SubnetId: !Ref PublicSubnet1
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Exportar las variables de CloudFormation al entorno de la EC2
          export DYNAMODB_TABLE_NAME="${myDynamoDBTable}"
          export AWS_REGION="${AWS::Region}"
          # Instalar AWS CLI y descargar el script
          yum install -y aws-cli
          wget -O /tmp/docker_setup.sh https://raw.githubusercontent.com/franjavi-upct-es/Proyecto-ICAP-AquaSense/main/Plantillas%20CloudFormation%20IaC/docker_setup.sh
          
          # Hacer el script ejecutable y ejecutarlo
          chmod +x /tmp/docker_setup.sh
          /tmp/docker_setup.sh
      InstanceInitiatedShutdownBehavior: terminate
      Tags:
        - Key: Name
          Value: proy-DockerInstance



######################
# Outputs section
######################
Outputs:

  VPCId:
    Value: !Ref VPC
    Export:
      Name: !Sub "${AWS::StackName}-VPCId"

  PublicSubnet1Id:
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnet1Id"

  PublicSubnet2Id:
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnet2Id"

  PrivateSubnet1Id:
    Value: !Ref PrivateSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnet1Id"

  PrivateSubnet2Id:
    Value: !Ref PrivateSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnet2Id"

  PrivateFlaskSecurityGroupId:
    Value: !Ref PrivateFlaskSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-PrivateFlaskSG"

  ALBSecurityGroupId:
    Value: !Ref ALBSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-ALBSecurityGroup"

  DynamoDBTableName:
    Value: !Ref myDynamoDBTable
    Export:
      Name: !Sub "${AWS::StackName}-DynamoDBTable"

  ARNLabrol:
    Value: !Ref ExistingRoleArn
    Export:
      Name: !Sub "${AWS::StackName}-ARNLabrol"