AWSTemplateFormatVersion: 2010-09-09
Description: Plantilla que crea la infraestructura ECS EC2 con awsvpc

Parameters:
  NetworkStackName:
    Description: Nombre de la pila de infraestructura base
    Type: String
    Default: proy-infraestructura-soporte

Resources:
  ###################
  # ECS Cluster
  ###################
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: proy-marmenor-cluster

  ECSLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Sub "{{resolve:ssm:/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id}}"
      InstanceType: t3.micro
      IamInstanceProfile: LabInstanceProfile
      SecurityGroups:
        - Fn::ImportValue: !Sub "${NetworkStackName}-PrivateFlaskSG"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo ECS_CLUSTER=${ECSCluster} >> /etc/ecs/ecs.config

  ECSAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: 2
      MaxSize: 5
      DesiredCapacity: 3
      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub "${NetworkStackName}-PrivateSubnet1Id"
        - Fn::ImportValue: !Sub "${NetworkStackName}-PrivateSubnet2Id"
      LaunchConfigurationName: !Ref ECSLaunchConfiguration
      Tags:
        - Key: Name
          Value: proy-ECS-I
          PropagateAtLaunch: true

  ###################################
  # Load Balancer
  ###################################
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: proy-marmenor-alb
      Subnets:
        - Fn::ImportValue: !Sub "${NetworkStackName}-PublicSubnet1Id"
        - Fn::ImportValue: !Sub "${NetworkStackName}-PublicSubnet2Id"
      SecurityGroups:
        - Fn::ImportValue: !Sub "${NetworkStackName}-ALBSecurityGroup"
      Scheme: internet-facing
      Type: application

  ###################################
  # Target Group
  ###################################
  ECSTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: proy-tg
      VpcId:
        Fn::ImportValue: !Sub "${NetworkStackName}-VPCId"
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: /health
      HealthCheckPort: "8080"
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: "200"

  ###################################
  # Listener
  ###################################
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ECSTargetGroup

  ###################################
  # Task
  ###################################
  ECSTaskDefinitionEC2:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: aquasense-api-task-ec2
      Cpu: 256
      Memory: 256
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - EC2
      # Rol dinámico usando AccountId
      ExecutionRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      TaskRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      ContainerDefinitions:
        - Name: proy-aquasense-api
          # IMAGEN AUTOMATIZADA AQUÍ:
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/aquasense-api:latest"
          PortMappings:
            - ContainerPort: 8080
          Environment:
            - Name: DYNAMODB_TABLE
              Value:
                Fn::ImportValue: !Sub "${NetworkStackName}-DynamoDBTable"
            - Name: AWS_REGION
              Value: !Ref AWS::Region
          Essential: true
          HealthCheck:
            Command:
              ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
            Interval: 30
            Timeout: 10
            Retries: 5
            StartPeriod: 60

  ###################################
  # ECS Service
  ###################################
  ECSServiceEC2:
    Type: AWS::ECS::Service
    DependsOn: ALBListener
    Properties:
      Cluster: !Ref ECSCluster
      LaunchType: EC2
      DesiredCount: 3
      TaskDefinition: !Ref ECSTaskDefinitionEC2
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - Fn::ImportValue: !Sub "${NetworkStackName}-PrivateSubnet1Id"
            - Fn::ImportValue: !Sub "${NetworkStackName}-PrivateSubnet2Id"
          SecurityGroups:
            - Fn::ImportValue: !Sub "${NetworkStackName}-PrivateFlaskSG"
      LoadBalancers:
        - ContainerName: proy-aquasense-api
          ContainerPort: 8080
          TargetGroupArn: !Ref ECSTargetGroup

######################
# Outputs section
######################

Outputs:
  LoadBalancerURL:
    Description: URL del Application Load Balancer para acceder a la API de AquaSense
    Value: !Sub "http://${ApplicationLoadBalancer.DNSName}"
    Export:
      Name: !Sub "${AWS::StackName}-LoadBalancerURL"

  APIEndpointTemp:
    Description: Endpoint para consultar temperatura media mensual
    Value: !Sub "http://${ApplicationLoadBalancer.DNSName}/temp?month=3&year=2017"

  APIEndpointSD:
    Description: Endpoint para consultar desviación estándar máxima mensual
    Value: !Sub "http://${ApplicationLoadBalancer.DNSName}/sd?month=3&year=2017"

  APIEndpointMaxDiff:
    Description: Endpoint para consultar diferencia de temperatura máxima mensual
    Value: !Sub "http://${ApplicationLoadBalancer.DNSName}/maxdiff?month=4&year=2017"

  APIEndpointMonths:
    Description: Endpoint para listar todos los meses disponibles
    Value: !Sub "http://${ApplicationLoadBalancer.DNSName}/months"

  APIEndpointHealth:
    Description: Endpoint de health check del servicio
    Value: !Sub "http://${ApplicationLoadBalancer.DNSName}/health"

  LoadBalancerDNS:
    Description: DNS del Load Balancer (sin protocolo)
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub "${AWS::StackName}-LoadBalancerDNS"
